format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[--](fg:#ffffff)\ 
$character"""

[directory]
style = "fg:#15bfe6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#1cad5d"
format = '[[ $symbol $branch ](fg:#1cad5d)]($style)'

[git_status]
style = "fg:#e0d41f"
format = '[[($all_status$ahead_behind )](fg:#e0d41f)]($style)'

[nodejs]
symbol = ""
style = "fg:#eded5a"
format = '[[ $symbol ($version) ](fg:#eded5a)]($style)'

[rust]
symbol = ""
style = "fg:#eded5a"
format = '[[ $symbol ($version) ](fg:#eded5a)]($style)'

[golang]
symbol = ""
style = "fg:#eded5a"
format = '[[ $symbol ($version) ](fg:#eded5a)]($style)'

[php]
symbol = ""
style = "fg:#eded5a"
format = '[[ $symbol ($version) ](fg:#eded5a)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
